In [34]:
#Import packages

import numpy as np
import pandas as pd

# For visualization purpose
import folium

In [35]:
# Retrieve LIVE COVID-19 Stats of India from Wikipedia
corona_stats = pd.read_html('https://en.wikipedia.org/wiki/COVID-19_pandemic_in_India#covid19-container',match='State/Union Territory')

#Convert to DataFrame
covid19_india_1 = pd.DataFrame(corona_stats[0])

covid19_india_1.head()

  [show all]viewtalkeditCOVID-19 pandemic in India by state and union territory  \
                                                          State/Union Territory
                                                                        35 / 36
0                        Andaman and Nicobar Islands
1                                     Andhra Pradesh
2                                  Arunachal Pradesh
3                                              Assam
4                                              Bihar

                                                             \
     Cases[a]  Deaths Recoveries  Active Unnamed: 5_level_1
    6,835,655 105,526  5,827,704 902,425 Unnamed: 5_level_2
0        3935      54       3696     185                NaN
1      734427    6086     678828   49513                NaN
2       11267      21       8396    2850                NaN
3  190,209[b]     785     157638   31786                NaN
4      191985     927     179732   11326                NaN


  Unnamed: 6_level_1 Unnamed: 7_level_1 Unnamed: 8_level_1
  Unnamed: 6_level_2 Unnamed: 7_level_2 Unnamed: 8_level_2
0                NaN                NaN                NaN
1                NaN                NaN                NaN
2                NaN                NaN                NaN
3                NaN                NaN                NaN
4                NaN                NaN                NaN

In [36]:
covid19_india_1.tail()

   [show all]viewtalkeditCOVID-19 pandemic in India by state and union territory  \
                                                           State/Union Territory
                                                                         35 / 36
33                                        Uttarakhand
34                                      Uttar Pradesh
35                                        West Bengal
36                           As of 9 October 2020[39]
37  Notes ^ Inclusive of foreign nationals ^ The M...

                                                       \
                                             Cases[a]
                                            6,835,655
33                                              52959
34                                             424326
35                                             280504
36                           As of 9 October 2020[39]
37  Notes ^ Inclusive of foreign nationals ^ The M...

                                                       \
                                               Deaths
                                              105,526
33                                                688
34                                               6200
35                                               5376
36                           As of 9 October 2020[39]
37  Notes ^ Inclusive of foreign nationals ^ The M...

                                                       \
                                           Recoveries
                                            5,827,704
33                                              43904
34                                             374972
35                                             246767
36                           As of 9 October 2020[39]
37  Notes ^ Inclusive of foreign nationals ^ The M...

                                                                          \
                                               Active Unnamed: 5_level_1
                                              902,425 Unnamed: 5_level_2
33                                               8367                NaN
34                                              43154                NaN
35                                              28361                NaN
36                           As of 9 October 2020[39]                NaN
37  Notes ^ Inclusive of foreign nationals ^ The M...                NaN


   Unnamed: 6_level_1 Unnamed: 7_level_1 Unnamed: 8_level_1
   Unnamed: 6_level_2 Unnamed: 7_level_2 Unnamed: 8_level_2
33                NaN                NaN                NaN
34                NaN                NaN                NaN
35                NaN                NaN                NaN
36                NaN                NaN                NaN
37                NaN                NaN                NaN

In [37]:
# cleaning COVID-19 Dataframe

# Removing unnecessary rows and columns
covid19_india = covid19_india_1.iloc[:-2,:-4]

# Renaming Attribute Names
covid19_india.columns = ['States','Total cases','Deaths','Recoveries','Active cases']

covid19_india.head()

                        States Total cases Deaths Recoveries Active cases
0  Andaman and Nicobar Islands        3935     54       3696          185
1               Andhra Pradesh      734427   6086     678828        49513
2            Arunachal Pradesh       11267     21       8396         2850
3                        Assam  190,209[b]    785     157638        31786
4                        Bihar      191985    927     179732        11326

In [38]:
covid19_india.tail()

           States Total cases Deaths Recoveries Active cases
31      Telangana      206644   1201     179075        26368
32        Tripura       27759    304      23066         4389
33    Uttarakhand       52959    688      43904         8367
34  Uttar Pradesh      424326   6200     374972        43154
35    West Bengal      280504   5376     246767        28361

In [39]:
# Retrieve latitude and longitude of states from Wikipedia
india_latlong_0 = pd.read_html('https://www.distancelatlong.com/distancecalculator/country/india',match='States')

#Convert to DataFrame
india_latlong_1 = pd.DataFrame(india_latlong_0 [0])

india_latlong_1.head()

                    States   Latitude  Longitude
0  Andaman And Nicobar (1)  11.667026  92.735983
1      Andhra Pradesh (20)  14.750429  78.570026
2    Arunachal Pradesh (1)  27.100399  93.616601
3                Assam (6)  26.749981  94.216667
4                Bihar (6)  25.785414  87.479973

In [40]:
india_latlong_1.tail()

                States   Latitude  Longitude
28     Tamil Nadu (19)  12.920386  79.150042
29         Tripura (1)  23.835404  91.279999
30  Uttar Pradesh (29)  27.599981  78.050006
31     Uttaranchal (1)  30.320409  78.050006
32    West Bengal (10)  22.580390  88.329947

In [41]:
covid19_india["States"].unique()

array(['Andaman and Nicobar Islands', 'Andhra Pradesh',
       'Arunachal Pradesh', 'Assam', 'Bihar', 'Chandigarh',
       'Chhattisgarh', 'Dadra and Nagar Haveli and Daman and Diu',
       'Delhi', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh',
       'Jammu and Kashmir', 'Jharkhand', 'Karnataka', 'Kerala', 'Ladakh',
       'Lakshadweep', 'Madhya Pradesh', 'Maharashtra', 'Manipur',
       'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Puducherry',
       'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana',
       'Tripura', 'Uttarakhand', 'Uttar Pradesh', 'West Bengal'],
      dtype=object)

In [42]:
india_latlong_1["States"].unique()

array(['Andaman And Nicobar (1)', 'Andhra Pradesh (20)',
       'Arunachal Pradesh (1)', 'Assam (6)', 'Bihar (6)',
       'Chandigarh (1)', 'Chhattisgarh (3)',
       'Dadra And Nagar Haveli (12)', 'Delhi (2)', 'Goa (1)',
       'Haryana (10)', 'Himachal Pradesh (2)', 'Jammu And Kashmir (4)',
       'Jharkhand (3)', 'Karnataka (16)', 'Kerala (5)', 'Lakshadweep (1)',
       'Madhya Pradesh (8)', 'Maharashtra (20)', 'Manipur (1)',
       'Meghalaya (1)', 'Mizoram (1)', 'Nagaland (1)', 'Orissa (6)',
       'Puducherry (1)', 'Punjab (6)', 'Rajasthan (12)', 'Sikkim (1)',
       'Tamil Nadu (19)', 'Tripura (1)', 'Uttar Pradesh (29)',
       'Uttaranchal (1)', 'West Bengal (10)'], dtype=object)

In [43]:
#Replace State names to match with ccordinates data

covid19_india['States']=covid19_india.States.replace({'and Daman and Diu': "","Islands" : "",},regex=True)
covid19_india.head(8)

                    States Total cases Deaths Recoveries Active cases
0     Andaman and Nicobar         3935     54       3696          185
1           Andhra Pradesh      734427   6086     678828        49513
2        Arunachal Pradesh       11267     21       8396         2850
3                    Assam  190,209[b]    785     157638        31786
4                    Bihar      191985    927     179732        11326
5               Chandigarh       12820    182      11190         1448
6             Chhattisgarh      131739   1134     103828        26777
7  Dadra and Nagar Haveli         3120      2       3010          108

In [44]:
#Cleaning coordinates data

india_latlong_1["States"]=india_latlong_1.States.replace({'Orissa': "Odisha","Uttaranchal" : "Uttarakhand","And " : "and "},regex=True)
india_latlong_1["States"]=india_latlong_1['States'].str.replace(r"\(.*\)","")
india_latlong_1["States"].unique()

array(['Andaman and Nicobar ', 'Andhra Pradesh ', 'Arunachal Pradesh ',
       'Assam ', 'Bihar ', 'Chandigarh ', 'Chhattisgarh ',
       'Dadra and Nagar Haveli ', 'Delhi ', 'Goa ', 'Haryana ',
       'Himachal Pradesh ', 'Jammu and Kashmir ', 'Jharkhand ',
       'Karnataka ', 'Kerala ', 'Lakshadweep ', 'Madhya Pradesh ',
       'Maharashtra ', 'Manipur ', 'Meghalaya ', 'Mizoram ', 'Nagaland ',
       'Odisha ', 'Puducherry ', 'Punjab ', 'Rajasthan ', 'Sikkim ',
       'Tamil Nadu ', 'Tripura ', 'Uttar Pradesh ', 'Uttarakhand ',
       'West Bengal '], dtype=object)

In [45]:
#Create dataframe for missing values in the coordinates data

states_latlong = pd.DataFrame({"States":["Gujarat", "Ladakh", "Telangana"], 
                    "Latitude":[22.309425, 34.209515, 17.123184 ],
                    "Longitude":[72.136230, 77.615112, 79.208824]}) 

#Append dataframe with coordinates data

india_latlong=india_latlong_1.append(states_latlong,ignore_index=True)
india_latlong.tail()

          States   Latitude  Longitude
31  Uttarakhand   30.320409  78.050006
32  West Bengal   22.580390  88.329947
33       Gujarat  22.309425  72.136230
34        Ladakh  34.209515  77.615112
35     Telangana  17.123184  79.208824

In [46]:
#Remove extra spaces from States to avoid any issues while merging

for df in (india_latlong, covid19_india):
    df['States'] = df['States'].str.strip()
    
#Merging the tables covid19 and coordinates 

india_data = pd.merge(india_latlong, covid19_india, how="inner", on ='States')
india_data.tail()

,States,Latitude,Longitude,Total cases,Deaths,Recoveries,Active cases
31,Uttarakhand,30.320409,78.050006,52959,688,43904,8367
32,West Bengal,22.580390,88.329947,280504,5376,246767,28361
33,Gujarat,22.309425,72.136230,146673,3531,126657,16485
34,Ladakh,34.209515,77.615112,4802,63,3511,1228
35,Telangana,17.123184,79.208824,206644,1201,179075,26368

In [47]:
india_data["States"].unique()

array(['Andaman and Nicobar', 'Andhra Pradesh', 'Arunachal Pradesh',
       'Assam', 'Bihar', 'Chandigarh', 'Chhattisgarh',
       'Dadra and Nagar Haveli', 'Delhi', 'Goa', 'Haryana',
       'Himachal Pradesh', 'Jammu and Kashmir', 'Jharkhand', 'Karnataka',
       'Kerala', 'Lakshadweep', 'Madhya Pradesh', 'Maharashtra',
       'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha',
       'Puducherry', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu',
       'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal',
       'Gujarat', 'Ladakh', 'Telangana'], dtype=object)

In [48]:
# Retrieve data from india_data table and plot it on the INDIA map
# Create the map zooming on INDIA,the lat and long of INDIA[20.5937,78.9629]

india = folium.Map(location = [20.5937,78.9629],zoom_start=5)

#add to map

for state,lat,long,total_cases,Death,Recov,Active in zip(list(india_data['States']),list(india_data['Latitude']),list(india_data['Longitude']),list(india_data['Total cases']),list(india_data['Deaths']),list(india_data['Recoveries']),list(india_data['Active cases'])):
    #create circle marker
    folium.CircleMarker(location = [lat,long],
                       radius = 5,
                       color='Red',
                       fill = True,
                       fill_color="Blue").add_to(india)
    #create marker
    folium.Marker(location = [lat,long],
                  # add information that need to be displayed on popup
                  popup=folium.Popup(('<strong><b>States  : '+state+'</strong> <br>' +
                    '<strong><b>Total Cases : '+total_cases+'</strong><br>' +
                    '<strong><font color= red>Deaths : </font>'+Death+'</strong><br>' +
                    '<strong><font color=green>Recoveries : </font>'+Recov+'</strong><br>' +
                    '<strong><font color=Orange>Active Cases : </font>'+Active+'</strong>')),max_width=200,tooltip='<strong>Click here to see Popup</strong>').add_to(india)

In [20]:
#show the map
india

In [49]:
covid19_india[covid19_india["States"]=="Kerala"]

    States Total cases  Deaths Recoveries Active cases
16  Kerala      253405  906[c]     160253        92246

In [50]:
#Retrieve LIVE COVID-19 stats of Kerala from wikipedia

corona_kerala=pd.read_html("https://en.wikipedia.org/wiki/COVID-19_pandemic_in_Kerala",match="District")

#Convert to DataFrame
covid19_kerala_1 = pd.DataFrame(corona_kerala[0])

covid19_kerala_1.head()

  vteCOVID-19 pandemic in Kerala by district                                   \
                                          S.            District Active cases
0                                          1           Ernakulam        11692
1                                          1  Thiruvananthapuram        11689
2                                        NaN           Kozhikode        10216
3                                        NaN              Kollam         8772
4                                        NaN            Thrissur         8393


  Recoveries Deaths Total cases Change since yesterday
0      13439     80       25219                    317
1      29923    290       41939                   1063
2      16477     84       26783                    433
3      10733     71       19580                    235
4      10688     59       19144                     75

In [51]:
covid19_kerala_1.tail()

   vteCOVID-19 pandemic in Kerala by district                            \
                                           S.                  District
11                                        NaN            Pathanamthitta
12                                        NaN                    Idukki
13                                        NaN                   Wayanad
14                   Total (all 14 districts)  Total (all 14 districts)
15                   As of 8 October 2020[62]  As of 8 October 2020[62]

                                                        \
                Active cases                Recoveries
11                      2950                      7004
12                      1301                      3320
13                      1143                      3371
14                     90582                    167256
15  As of 8 October 2020[62]  As of 8 October 2020[62]

                                                        \
                      Deaths               Total cases
11                         6                      9961
12                         5                      4628
13                         5                      4519
14                       930                    258850
15  As of 8 October 2020[62]  As of 8 October 2020[62]


      Change since yesterday
11                       156
12                        52
13                         2
14                      1582
15  As of 8 October 2020[62]

In [52]:
# cleaning Covid19 Dataframe

# Removing unnecessary rows and unnecessary columns
covid19_kerala = covid19_kerala_1.iloc[: -2,1:-1]

# Renaming Attribute Names
covid19_kerala.columns = ['District','Active cases','Recoveries','Deaths','Total cases']

covid19_kerala.head()

             District Active cases Recoveries Deaths Total cases
0           Ernakulam        11692      13439     80       25219
1  Thiruvananthapuram        11689      29923    290       41939
2           Kozhikode        10216      16477     84       26783
3              Kollam         8772      10733     71       19580
4            Thrissur         8393      10688     59       19144

In [53]:
covid19_kerala.tail()

          District Active cases Recoveries Deaths Total cases
9         Kottayam         4931       8848     28       13807
10       Kasaragod         4351       9143     60       13558
11  Pathanamthitta         2950       7004      6        9961
12          Idukki         1301       3320      5        4628
13         Wayanad         1143       3371      5        4519

In [54]:
# Retrieve latitude and longitude of districts from Wikipedia

kerala_latlong_0=pd.read_html("https://www.imdtvm.gov.in/index.php?option=com_content&task=view&id=1&Itemid=26",match="Raingauge Station")

#Convert to DataFrame
kerala_latlong_1 = pd.DataFrame(kerala_latlong_0[1])

kerala_latlong_1.head()

                            0                   1             2              3
0           Raingauge Station            District  Latitude (N)  Longitude (E)
1               NEYYATTINKARA  THIRUVANANTHAPURAM         08.38          77.08
2          THIRUVANANTHAPURAM  THIRUVANANTHAPURAM         08.47          76.95
3  THIRUVANANTHAPURAM AIRPORT  THIRUVANANTHAPURAM         08.48          76.92
4                  NEDUMANGAD  THIRUVANANTHAPURAM         08.60          77.00

In [55]:
kerala_latlong_1.tail(8)

                 0            1      2      3
80    CHERUTHAZHAM       KANNUR  12.06  75.25
81         HOSDURG    KASARAGOD  12.30  75.10
82           KUDLU    KASARAGOD  12.50  75.00
83       KASARAGOD    KASARAGOD  12.50  74.99
84         MINICOY  LAKSHADWEEP  08.30  73.15
85       KAVARATTI  LAKSHADWEEP  10.53  72.62
86  AGATHI AIRPORT  LAKSHADWEEP  10.85  72.47
87           AMINI  LAKSHADWEEP  11.12  72.73

In [56]:
# cleaning Covid19 Dataframe
a=kerala_latlong_1[kerala_latlong_1.index.isin([0])].values.tolist()
a[0]

['Raingauge Station', 'District', 'Latitude (N)', 'Longitude (E)']

In [57]:
# Removing unnecessary rows at the tail and Unnecessary columns
kerala_latlong = kerala_latlong_1.iloc[1:-3,:]

# Renaming Attribute Names for simplicity
kerala_latlong.columns=a[0]

kerala_latlong.head()

            Raingauge Station            District Latitude (N) Longitude (E)
1               NEYYATTINKARA  THIRUVANANTHAPURAM        08.38         77.08
2          THIRUVANANTHAPURAM  THIRUVANANTHAPURAM        08.47         76.95
3  THIRUVANANTHAPURAM AIRPORT  THIRUVANANTHAPURAM        08.48         76.92
4                  NEDUMANGAD  THIRUVANANTHAPURAM        08.60         77.00
5                     VARKALA  THIRUVANANTHAPURAM        08.74         76.72

In [59]:
#Select one record per district

kerala_latlong1 = kerala_latlong.loc[kerala_latlong["Raingauge Station"] == kerala_latlong["District"]]
kerala_latlong1.head(14)

     Raingauge Station            District Latitude (N) Longitude (E)
2   THIRUVANANTHAPURAM  THIRUVANANTHAPURAM        08.47         76.95
18           ALAPPUZHA           ALAPPUZHA        09.55         76.33
21            KOTTAYAM            KOTTAYAM        09.58         76.52
27              IDUKKI              IDUKKI        09.83         76.92
43            THRISSUR            THRISSUR        10.52         76.22
53            PALAKKAD            PALAKKAD        10.77         76.65
65           KOZHIKODE           KOZHIKODE        11.25         75.78
76              KANNUR              KANNUR        11.87         75.37
83           KASARAGOD           KASARAGOD        12.50         74.99